name: Deploy to ftp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ActionsRML/get-PR-latest-commit@master

      - name: Install git-ftp
        run: |
          sudo apt-get update
          sudo apt-get install git-ftp -y

      - name: Set FTP access
        run: |
          git config git-ftp.url "${{ secrets.FTP_URL }}"
          git config git-ftp.user "${{ secrets.FTP_USER }}"
          git config git-ftp.password "${{ secrets.FTP_PASS }}"

      - name: Catchup FTP
        run: |
          git ftp catchup -v

      - name: Push new version
        run: |
          git ftp push -f -vv -c "${{ steps.get-latest-commit.outputs.latest_commit_sha }}"
