name: Deploy to ftp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install git-ftp
        run: |
          sudo apt-get install git-ftp -y

      - name: Set FTP access
        run: |
          git config git-ftp.url "${{ secrets.FTP_URL }}"
          git config git-ftp.user "${{ secrets.FTP_USER }}"
          git config git-ftp.password "${{ secrets.FTP_PASS }}"

      # - name: Catchup FTP
      #   run: |
      #     git ftp catchup -v

      - name: Push new version
        run: |
          git ftp push --auto-init -v
