name: Deploy to ftp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install git-ftp
        run: |
          mkdir -p $HOME/.local/bin
          curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > $HOME/.local/bin/git-ftp
          chmod 755 ~/.local/bin/git-ftp
          export PATH=$PATH:$HOME/.local/bin
          $HOME/.local/bin/git-ftp --version

      - name: Set FTP access
        run: |
          git config git-ftp.url "${{ secrets.FTP_URL }}"
          git config git-ftp.user "${{ secrets.FTP_USER }}"
          git config git-ftp.password "${{ secrets.FTP_PASS }}"

      # - name: Catchup FTP
      #   run: |
      #     $HOME/.local/bin/git-ftp catchup -v

      # - name: SHA
      #   run: echo $GITHUB_SHA

      - name: Push new version
        run: |
          $HOME/.local/bin/git-ftp push --auto-init -f -v -c $GITHUB_SHA
